# Generated by Django 4.2.3 on 2023-08-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
